spring.application.name=BACKEND
spring.datasource.url=jdbc:postgresql://localhost:5432/db_OjoCiudadano
spring.datasource.username=postgres
spring.datasource.password=Postgre
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#No envia todo el trace al usuario
server.error.include-stacktrace=never

ip.frontend=http://localhost:4200

jwt.secret=0C/ZZj9OCW7Q74lUM200BayaFq6u12EKyps4NLFQNufowubX5nE1DQT8XRdwv0zUBp7Tns1yhYlwzUCm3maQkg==

  # 0C/ZZj9OCW7Q74lUM200BayaFq6u12EKyps4NLFQNufowubX5nE1DQT8XRdwv0zUBp7Tns1yhYlwzUCm3maQkg==

# $2a$12$6TeQTMaS.re3ByQQ3RYQDuNcmTMvh2wGi0pjJjf2AE9gWSearE8zi


# $2a$12$Lz4QUJCAII03e6ev.u22Yu.qaKuoOn6BNuXSWFj.uh40OBEk6q/pG